name: ecr
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/ecr?ref=release/1.12.0&depth=1
parameters:
  - name: repository_name
    value: "ecr-repository-1"
  - name: image_tag_mutability
    value: "MUTABLE"
  - name: image_scan_on_push
    value: True
  - name: encryption
    value: "KMS_MANAGED"