name: app-reg
path: git::https://github.com/awslabs/idf-modules.git//modules/service-catalog/app-registry?ref=release/1.12.0&depth=1
parameters:
  - name: solution-id
    value: id
  - name: solution-name
    value: name
  - name: solution-version
    value: version