name: dummy
path: git::https://github.com/awslabs/idf-modules.git//modules/dummy/blank?ref=release/1.12.0&depth=1
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: testingRegionParams
    valueFrom:
      parameterValue: myTestRegionParam
  - name: testingGlobalParams
    valueFrom:
      parameterValue: myTestGlobalParam