name: buckets
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/buckets?ref=release/1.12.0&depth=1
targetAccount: primary
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: RETAIN
---
name: opensearch
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/opensearch?ref=release/1.12.0&depth=1
targetAccount: primary
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: RETAIN
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
---
name: opensearch-s
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/opensearch-serverless?ref=release/1.12.0&depth=1
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
---
name: efs
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/efs?ref=release/1.12.0&depth=1
targetAccount: primary
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: retention-type
    value: RETAIN
---
name: fsx-lustre
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/fsx-lustre?ref=release/1.12.0&depth=1
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: private_subnet_ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
  - name: fs_deployment_type
    value: PERSISTENT_1
  - name: storage_throughput
    value: 50